core/urls.py
from django.urls import path
from core.views import *


app_name = 'core'

urlpatterns = [
    path("", index, name='index'),
    path('task/<int:task_id>/', task_view, name='task'),
    path('new-task/', create_task, name='new-task')
    # path('signup/', register, name='signup'),
    # path('signin/', login, name='signin'),
]

taskmanager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('user/', include('userauths.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

userauths/urls.py
from django.urls import path
from userauths.views import *

app_name = 'userauths'

urlpatterns = [
    path("sign-up", register, name='sign-up'),
    path("sign-in", login_view, name='sign-in'),
    path("logout", logout_view, name='logout'),
    path('verify-email/<str:username>/', verify_email, name='verify-email'),
    path('resend-otp/', resend_otp, name='resend-otp'),
    # path('activate-user/<uidb64>/<token>', activate_user, name='activate'),
    # path('signup/', register, name='signup'),
    # path('signin/', login, name='signin'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} My site {% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <style>
        /* CSS transitions for smooth animation */
        .animated-message {
            transition: transform 1s ease-in-out;
        }
    
        /* Class to apply animation */
        .slide-up {
            transform: translateY(-220%);
        }

        .card-body .p-3 {
            transition: box-shadow 0.5s ease; /* Set default transition on box-shadow */
        }

        .card-body .p-3:hover {
            cursor: pointer;
            box-shadow: 0px 5px 8px 0px rgba(0, 0, 0, 0.3);
        }

            @media (min-width: 1200px){
            .container {
                max-width: 100%;
            }
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg" style="box-shadow: 0px 5px 5px 0px rgba(0, 0, 0, 0.1);">
        <div class="container-fluid">
            <div>
                <!-- <ul class="navbar-nav" style="color: black;">
                    <li class="nav-item">
                        <a class="nav-link" href="">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="">Post</a>
                    </li>
                </ul> -->
                <ul class="navbar-nav" style="color: black;">
                    <li class="nav-item">
                        <div style="background: linear-gradient(135deg, #ab15e7, #0992ee); width: max-content; padding: 5px 20px 1px 20px;color:aliceblue; border-radius: 25px;">
                            <h4><b>Teamify😄</b></h4>
                        </div>
                    </li>
                </ul>
            </div>
            <div>
                <ul class="navbar-nav" style="gap: 50px;">
                    {% if user.is_superuser %}
                    <li class="nav-item">
                        <a href="{% url 'core:new-task' %}" class="btn btn-primary btn-block">Add new</a>
                    </li>
                    {% endif %}
                    <li>
                        <!-- <div class="card-actions float-right"> -->
                            <div class="dropdown show">
                            <a href="#" data-toggle="dropdown" data-display="static">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-more-horizontal align-middle">
                            <circle cx="12" cy="19" r="2"></circle>
                            <circle cx="19" cy="19" r="2"></circle>
                            <circle cx="5" cy="19" r="2"></circle>
                            </svg>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Settings</a>
                            <a class="dropdown-item" href="{% url 'userauths:logout' %}">Logout</a>
                            </div>
                            <!-- </div> -->
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% if messages %}

            {% for message in messages %}

            <center><div class="alert alert-{{message.tags}} form-control text-fluid animated-message" style="height: 50px; z-index: 99; position: absolute; width: 100%">    
            <strong id="strong" style="color: black;">{{message}}</strong>
            </div></center>

            {% endfor %}

            {% endif %}


            <script>
                setTimeout (() => {
                    $(".animated-message").addClass("slide-up");
                }, 3000)
            </script>

    <div class="container">{% block content %} {% endblock %}</div>
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script> -->
    <!-- <script src="{% static 'js/home.js' %}"></script> -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.1/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript">
	
</script>
</body>
</html>

templates/create_task.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Teamify - Creating Task</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.1/dist/css/bootstrap.min.css" rel="stylesheet">
<!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"> -->
<!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"> -->
<link rel="stylesheet" href="{% static 'css/task.css' %}">
<!-- <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.8/css/line.css"> -->
</head>
<body>
<div class="container">
<div class="row">
<div class="col-md-12">
    <center><div style="text-align: center; background: linear-gradient(135deg, #ab15e7, #0992ee); width: max-content; padding: 0 15px; height: 45px; color:aliceblue; border-radius: 50px;"><h2>Create Task</h2></div></center>

<div class="tab-pane" id="edit">
<form style="margin-top: 4vw;" method="post">
    {% csrf_token %}
<div class="form-group row">
<label class="col-lg-3 col-form-label form-control-label">Title</label>
<div class="col-lg-9">
<input class="form-control" type="text" name="title" placeholder="Task title" required>
</div>
</div>
<div class="form-group row">
    <label class="col-lg-3 col-form-label form-control-label">Description</label>
    <div class="col-lg-9">
    <textarea class="form-control" type="text" placeholder="Description" name="description" cols="30" rows="5" required></textarea>
    </div>
</div>
<!-- 
<div class="form-group row">
<label class="col-lg-3 col-form-label form-control-label">Change profile</label>
<div class="col-lg-9">
<input class="form-control" type="file">
</div>
</div> -->
<div class="form-group row">
<label class="col-lg-3 col-form-label form-control-label">Due date</label>
<div class="col-lg-9">
<input class="form-control" type="date" name="due_date" required>
</div>
</div>
<!-- <div class="form-group row">
<label class="col-lg-3 col-form-label form-control-label"></label>
<div class="col-lg-6">
<input class="form-control" type="text" value placeholder="City">
</div>
<div class="col-lg-3">
<input class="form-control" type="text" value placeholder="State">
</div>
</div> -->
<div class="form-group row">
<label class="col-lg-3 col-form-label form-control-label">Priority</label>
<div class="col-lg-9">
    <select class="form-control" name="priority" required>
        <option value="Low">Low</option>
        <option value="Medium">Medium</option>
        <option value="High">High</option>
    </select>
</div>
</div>
<div class="form-group row">
<label class="col-lg-3 col-form-label form-control-label">Labels</label>
<div class="col-lg-9">
    <select class="form-control" name="labels" multiple>
        {% for label in labels %}
            <option value="{{ label.id }}">{{ label.name }}</option>
        {% endfor %}
    </select>
    <small style="color: rgb(101, 106, 126);">Hold down “Control”, or “Command” on a Mac, to select more than one.</small>
</div>
</div>
<div class="form-group row">
    <label class="col-lg-3 col-form-label form-control-label">Individual assignee</label>
    <div class="col-lg-9">
        <select class="form-control" name="assignee_id">
            <option value="">None</option>
            {% for user in all_users %}
                <option value="{{ user.id }}">{{ user.username }}</option>
            {% endfor %}
        </select>
        <!-- <small style="color: rgb(101, 106, 126);">Hold down “Control”, or “Command” on a Mac, to select more than one.</small> -->
    </div>
</div>
<div class="form-group row">
    <label class="col-lg-3 col-form-label form-control-label">Team</label>
    <div class="col-lg-9">
        <select class="form-control" name="assignee_team_id">
            <option value="">None</option>
            {% for team in teams %}
                <option value="{{ team.id }}">{{ team.name }}</option>
            {% endfor %}
        </select>
        <!-- <small style="color: rgb(101, 106, 126);">Hold down “Control”, or “Command” on a Mac, to select more than one.</small> -->
    </div>
</div>
<div class="form-group row">
    <label class="col-lg-3 col-form-label form-control-label">Phase</label>
    <div class="col-lg-9">
        <select class="form-control" name="category">
            {% for category, category_display in categories %}
                <option value="{{ category }}">{{ category_display }}</option>
            {% endfor %}
        </select>
        <!-- <small style="color: rgb(101, 106, 126);">Hold down “Control”, or “Command” on a Mac, to select more than one.</small> -->
    </div>
</div>
<div class="form-group row">
<label class="col-lg-3 col-form-label form-control-label">Created by</label>
<div class="col-lg-9">
    <select class="form-control" name="created_by_id">
        {% for user in users %}
            <option value="{{ user.id }}">{{ user }}</option>
        {% endfor %}
    </select>
    <!-- <small style="color: rgb(101, 106, 126);">Hold down “Control”, or “Command” on a Mac, to select more than one.</small> -->
</div>
</div>
<div class="form-group row">
<label class="col-lg-3 col-form-label form-control-label"></label>
<div class="col-lg-9">
<a class="btn btn-secondary" href="{% url 'core:index' %}">Go back</a>
<button type="submit" class="btn btn-primary">Create</button>
</div>
</div>
</form>
</div>
</div>
</div>
</div>
<script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.1/dist/js/bootstrap.bundle.min.js"></script>
<!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"></script> -->
<script type="text/javascript">
	
</script>
</body>
</html>

templates/login.html
{% load static %}

<!DOCTYPE html>
<!-- Coding By CodingNepal - codingnepalweb.com -->
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> Taskmanager Sign In </title>

        <!-- CSS -->
        <link rel="stylesheet" href="{% static 'css/register.css' %}">
                
        <!-- Boxicons CSS -->
        <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>

        <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"> -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
        <style>
            /* CSS transitions for smooth animation */
            .animated-message {
                transition: transform 1s ease-in-out;
            }

            /* Class to apply animation */
            .slide-up {
                transform: translateY(-220%);
            }
        </style>
                        
    </head>
    <body>
        {% if messages %}

        {% for message in messages %}

        <!-- <center><div class="alert alert-{{message.tags}} col-lg-8 col-md-8 col-sm-8 col-xs-8 form-control text-fluid animated-message" style="height: 50px; width: 100%; z-index: 99; position: absolute;">    
        <strong id="strong" style="color: black;">{{message}}</strong>
        </div></center> -->

        <div class="alert alert-{{message.tags}} col-lg-8 col-md-8 col-sm-8 col-xs-8 form-control text-fluid animated-message" style="height: 50px; width: 100%; z-index: 99; position: absolute;">    
        <center><div style="width: 20vw; padding: 10px 10px; font-size: 14px; height:50px; background:white; border-radius: 25px; align-items: center; justify-content: center; display:flex;">
        <strong id="strong" style="color: black;">{{message}}</strong>
        </div></center>
        </div>

        {% endfor %}

        {% endif %}


        <section class="container forms">
            <div class="form login">
                <div class="form-content">
                    <header>Login</header>
                    <form action="#" method="post">
                        {% csrf_token %}
                        <div class="field input-field">
                            <input type="email" placeholder="Email" class="input" name="email">
                        </div>

                        <div class="field input-field">
                            <input type="password" placeholder="Password" class="password" name="password">
                            <i class='bx bx-hide eye-icon'></i>
                        </div>

                        <div class="form-link">
                            <a href="#" class="forgot-pass">Forgot password?</a>
                        </div>

                        <div class="field button-field">
                            <button>Login</button>
                        </div>
                    </form>

                    <div class="form-link">
                        <span>Don't have an account? <a href="{% url 'userauths:sign-up' %}" class="link signup-link">Signup</a></span>
                    </div>
                </div>

                <div class="line"></div>

                <div class="media-options">
                    <a href="/accounts/github/login/?process=login" class="field facebook">
                        <i class='bx bxl-github facebook-icon'></i>
                        <span>Login with Github</span>
                    </a>
                </div>

                <div class="media-options">
                    <a href="/accounts/google/login/?process=login" class="field google">
                        <!-- <img src="#" alt="" class="google-img"> -->
                        <i class="bx facebook-icon"><svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="30" height="30" viewBox="0 0 48 48">
                            <path fill="#FFC107" d="M43.611,20.083H42V20H24v8h11.303c-1.649,4.657-6.08,8-11.303,8c-6.627,0-12-5.373-12-12c0-6.627,5.373-12,12-12c3.059,0,5.842,1.154,7.961,3.039l5.657-5.657C34.046,6.053,29.268,4,24,4C12.955,4,4,12.955,4,24c0,11.045,8.955,20,20,20c11.045,0,20-8.955,20-20C44,22.659,43.862,21.35,43.611,20.083z"></path><path fill="#FF3D00" d="M6.306,14.691l6.571,4.819C14.655,15.108,18.961,12,24,12c3.059,0,5.842,1.154,7.961,3.039l5.657-5.657C34.046,6.053,29.268,4,24,4C16.318,4,9.656,8.337,6.306,14.691z"></path><path fill="#4CAF50" d="M24,44c5.166,0,9.86-1.977,13.409-5.192l-6.19-5.238C29.211,35.091,26.715,36,24,36c-5.202,0-9.619-3.317-11.283-7.946l-6.522,5.025C9.505,39.556,16.227,44,24,44z"></path><path fill="#1976D2" d="M43.611,20.083H42V20H24v8h11.303c-0.792,2.237-2.231,4.166-4.087,5.571c0.001-0.001,0.002-0.001,0.003-0.002l6.19,5.238C36.971,39.205,44,34,44,24C44,22.659,43.862,21.35,43.611,20.083z"></path>
                            </svg></i>
                        <span>Login with Google</span>
                    </a>
                </div>

            </div>

        </section>

        <!-- JavaScript -->

        <script>
            setTimeout (() => {
                $(".animated-message").addClass("slide-up");
            }, 3000)
        </script>    

        <script src="{% static 'js/register.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    </body>
</html>

templates/register.html
{% load static %}

<!DOCTYPE html>
<!-- Coding By CodingNepal - codingnepalweb.com -->
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> Taskmanager Sign Up </title>

        <!-- CSS -->

        <link rel="stylesheet" href="{% static 'css/register.css' %}">
        
        <!-- Boxicons CSS -->
        <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
        <style>
            /* CSS transitions for smooth animation */
            .animated-message {
                transition: transform 1s ease-in-out;
            }

            /* Class to apply animation */
            .slide-up {
                transform: translateY(-220%);
            }
        </style>
                        
    </head>
    <body>
        
        {% if messages %}

        {% for message in messages %}

        <!-- <center><div class="alert alert-{{message.tags}} col-lg-8 col-md-8 col-sm-8 col-xs-8 form-control text-fluid animated-message" style="height: 50px; width: 100%; z-index: 99; position: absolute;">    
        <strong id="strong" style="color: black;">{{message}}</strong>
        </div></center> -->

        <div class="alert alert-{{message.tags}} col-lg-8 col-md-8 col-sm-8 col-xs-8 form-control text-fluid animated-message" style="height: 50px; width: 100%; z-index: 99; position: absolute;">    
        <center><div style="width: 15vw; height:50px; background:white; border-radius: 25px; align-items: center; justify-content: center; display:flex;">
        <strong id="strong" style="color: black;">{{message}}</strong>
        </div></center>
        </div>

        {% endfor %}

        {% endif %}

        
        <section class="container forms" style="height: 70vw;">

            <!-- Signup Form -->

            <div class="form login" style="height: max-content; position: relative;">
                <div class="form-content">
                    <header>Signup</header>
                    <form action="#" method="post">
                        {% csrf_token %}

                            {% for field in form %}

                                {% if field.errors %}

                                {{ field }}

                                <small style="text-decoration: none; color: red;">{{ field.errors }}</small>
                                <br>

                                {% else %}
                                    {{ field }}
                                    <!-- <small style="text-decoration: none; color: red;">Hello testing...</small> -->
                                {% endif %}
                            
                            {% endfor %}

                        <!-- <div class="field input-field">
                            <input type="email" placeholder="Email" class="input">
                        </div>

                        <div class="field input-field">
                            <input type="password" placeholder="Create password" class="password">
                        </div>

                        <div class="field input-field">
                            <input type="password" placeholder="Confirm password" class="password">
                            <i class='bx bx-hide eye-icon'></i>
                        </div>

                        <div class="field button-field">
                            <button>Signup</button>
                        </div> -->
                        <div class="field button-field">
                            <a href="{% url 'userauths:sign-up' %}"><button>Signup</button></a>
                        </div>
                    </form>

                    <div class="form-link">
                        <span>Already have an account? <a href="{% url 'userauths:sign-in' %}" class="link login-link">Login</a></span>
                    </div>
                </div>

                <div class="line"></div>

                <div class="media-options">
                    <a href="/accounts/github/login/?process=login" class="field facebook">
                        <i class='bx bxl-github facebook-icon'></i>
                        <span>Sign up with Github</span>
                    </a>
                </div>

                <div class="media-options">
                    <a href="/accounts/google/login/?process=login" class="field google">
                        <!-- <img src="#" alt="" class="google-img"> -->
                        <i class="bx facebook-icon"><svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="30" height="30" viewBox="0 0 48 48">
                            <path fill="#FFC107" d="M43.611,20.083H42V20H24v8h11.303c-1.649,4.657-6.08,8-11.303,8c-6.627,0-12-5.373-12-12c0-6.627,5.373-12,12-12c3.059,0,5.842,1.154,7.961,3.039l5.657-5.657C34.046,6.053,29.268,4,24,4C12.955,4,4,12.955,4,24c0,11.045,8.955,20,20,20c11.045,0,20-8.955,20-20C44,22.659,43.862,21.35,43.611,20.083z"></path><path fill="#FF3D00" d="M6.306,14.691l6.571,4.819C14.655,15.108,18.961,12,24,12c3.059,0,5.842,1.154,7.961,3.039l5.657-5.657C34.046,6.053,29.268,4,24,4C16.318,4,9.656,8.337,6.306,14.691z"></path><path fill="#4CAF50" d="M24,44c5.166,0,9.86-1.977,13.409-5.192l-6.19-5.238C29.211,35.091,26.715,36,24,36c-5.202,0-9.619-3.317-11.283-7.946l-6.522,5.025C9.505,39.556,16.227,44,24,44z"></path><path fill="#1976D2" d="M43.611,20.083H42V20H24v8h11.303c-0.792,2.237-2.231,4.166-4.087,5.571c0.001-0.001,0.002-0.001,0.003-0.002l6.19,5.238C36.971,39.205,44,34,44,24C44,22.659,43.862,21.35,43.611,20.083z"></path>
                            </svg></i>
                        <span>Sign up with Google</span>
                    </a>
                </div>

            </div>
        </section>

        <script>
            setTimeout (() => {
                $(".animated-message").addClass("slide-up");
            }, 3000)
        </script>

        <!-- JavaScript -->
        <script src="{% static 'js/register.js' %}"></script>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

    </body>
</html>

templates/resend-otp.html
{% load static %}

<!DOCTYPE html>
<!-- Coding By CodingNepal - codingnepalweb.com -->
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> Resend OTP </title>

        <!-- CSS -->
        <link rel="stylesheet" href="{% static 'css/register.css' %}">
                
        <!-- Boxicons CSS -->
        <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>
        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
        <style>
            /* CSS transitions for smooth animation */
            .animated-message {
                transition: transform 1s ease-in-out;
            }

            /* Class to apply animation */
            .slide-up {
                transform: translateY(-220%);
            }
        </style>
                        
    </head>
    <body>
        
        {% if messages %}

        {% for message in messages %}

        <!-- <center><div class="alert alert-{{message.tags}} col-lg-8 col-md-8 col-sm-8 col-xs-8 form-control text-fluid animated-message" style="height: 50px; width: 100%; z-index: 99; position: absolute;">    
        <strong id="strong" style="color: black;">{{message}}</strong>
        </div></center> -->

        <div class="alert alert-{{message.tags}} col-lg-8 col-md-8 col-sm-8 col-xs-8 form-control text-fluid animated-message" style="height: 50px; width: 100%; z-index: 99; position: absolute;">    
        <center><div style="width: 30%; padding: 10px 10px; height:50px; background:white; border-radius: 25px; align-items: center; justify-content: center; display:flex;">
        <strong id="strong" style="color: black; font-size: 14px;">{{message}}</strong>
        </div></center>
        </div>

        {% endfor %}

        {% endif %}

        <section class="container forms">
            <div class="form login">
                <div class="form-content">
                    <header>Resent OTP</header>
                    <form action="#" method="post">
                        {% csrf_token %}
                        <div class="field input-field">
                            <input type="email" placeholder="Enter Email" class="input" name="otp_email">
                        </div>

                        <div class="field button-field">
                            <button type="submit">Resent OTP</button>
                        </div>
                    </form>
                </div>

            </div>

        </section>

        <script>
            setTimeout (() => {
                $(".animated-message").addClass("slide-up");
            }, 4000)
        </script>    

        <script src="{% static 'js/register.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
        
    </body>
</html>

templates/verify-token.html
{% load static %}

<!DOCTYPE html>
<!-- Coding By CodingNepal - codingnepalweb.com -->
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> OTP verification </title>

        <!-- CSS -->
        <link rel="stylesheet" href="{% static 'css/register.css' %}">
                
        <!-- Boxicons CSS -->
        <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>
        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
        <style>
            /* CSS transitions for smooth animation */
            .animated-message {
                transition: transform 1s ease-in-out;
            }

            /* Class to apply animation */
            .slide-up {
                transform: translateY(-220%);
            }
        </style>
                        
    </head>
    <body>
        
        {% if messages %}

        {% for message in messages %}

        <!-- <center><div class="alert alert-{{message.tags}} col-lg-8 col-md-8 col-sm-8 col-xs-8 form-control text-fluid animated-message" style="height: 50px; width: 100%; z-index: 99; position: absolute;">    
        <strong id="strong" style="color: black;">{{message}}</strong>
        </div></center> -->

        <div class="alert alert-{{message.tags}} col-lg-8 col-md-8 col-sm-8 col-xs-8 form-control text-fluid animated-message" style="height: 50px; width: 100%; z-index: 99; position: absolute;">    
        <center><div style="width: 30%; padding: 10px 10px; height:50px; background:white; border-radius: 25px; align-items: center; justify-content: center; display:flex;">
        <strong id="strong" style="color: black; font-size: 14px;">{{message}}</strong>
        </div></center>
        </div>

        {% endfor %}

        {% endif %}

        <section class="container forms">
            <div class="form login">
                <div class="form-content">
                    <header>Email verify</header>
                    <form action="#" method="post">
                        {% csrf_token %}
                        <div class="field input-field">
                            <input type="text" placeholder="Enter OTP" class="input" name="otp_code">
                        </div>

                        <div class="field button-field">
                            <button type="submit">Activate account</button>
                        </div>
                    </form>

                    <div class="form-link">
                        <span style="font-size: 13px;">An OTP has been send to your email '{{email}}' <a href="{% url 'userauths:resend-otp' %}" class="link signup-link">Resend OTP</a></span>
                    </div>
                </div>

            </div>

        </section>

        <script>
            setTimeout (() => {
                $(".animated-message").addClass("slide-up");
            }, 4000)
        </script>    

        <script src="{% static 'js/register.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
        
    </body>
</html>